project:
  type: website

website:
  title: "Music Performance Analytics"
  toc: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: theory_vs_performance_plot.qmd
        text: Theory vs Performance Plot
      - href: model.qmd
        text: Model Details
      - href: sources.qmd
        text: Sources
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css